### ISSUE TITLE
How to Promote package that was just pushed to the feed?

### ISSUE THREAD

**Issue by asarapas** [renevanosnabrugge/vsts-promotepackage-task#11]
Hi, our use case is to have these steps in the Build Pipeline:

- Restore
- Pack
- Push

Once these steps done we would like to Promote freshly pushed package to the @Prerelease view. Extension does not allow to use variables to specify version. Is any other way I could achieve this?

**Comment by renevanosnabrugge** [comment]
Does a linked variabele work ? So you can set iT on pipeline level?

Verstuurd vanaf mijn iPhone

Op 19 dec. 2018 om 11:57 heeft Algis <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Hi, our use case is to have these steps in the Build Pipeline:

  *   Restore
  *   Pack
  *   Push

Once these steps done we would like to Promote freshly pushed package to the @prerelease<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fprerelease&data=02%7C01%7C%7C84ea366c186a4206071b08d665a0ce9b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636808138661576899&sdata=De4rEVZsUmY2DYIcIay%2BowEBQZ1qsc3wRo%2BSvokPdfo%3D&reserved=0> view. Extension does not allow to use variables to specify version. Is any other way I could achieve this?

**Comment by asarapas** [comment]
> Does a linked variabele work ? So you can set iT on pipeline level?

Thanks for the hint. It looks really promising, but I'm still getting error: This setting is invalid. Select a valid option from the dropdown.

Here is what I have done:

- Created Pipeline Variable "Parameters.BuildNo" and set value to "$(Build.BuildNumber)"
- Added "Promote package to PreRelease View" Task, selected Feed, Package and View from the dropdowns;
- In Link Settings Selected "Package Version" and in "The pipeline parameter to link to this setting" field typed "Parameters.BuildNo"
- YAML of the Promote Package task looks like this:
```
variables:
  Parameters.BuildNo: '$(Build.BuildNumber)'
steps:
- task: rvo.vsts-promotepackage-task.vsts-promotepackage-task.rvo-vsts-promotepackage-task@1
  displayName: 'Promote package to PreRelease View'
  inputs:
    feed: 'GUID...'
    definition: 'GUID...'
    version: '$(Parameters.BuildNo)'
    releaseView: 'GUID...'

```
- At this stage Save of the configuration is disabled and below Pipeline there is error: "Some settings need attention"
- Clicking on that I see Package version defaulted to the Last Build and Error message I have mentioned earlier: "This setting is invalid. Select a valid option from the dropdown."
