### ISSUE TITLE
Promote if stable?

### ISSUE THREAD

**Issue by onovotny** [renevanosnabrugge/vsts-promotepackage-task#31]
My scenario is this -- I want to always promote packages to the Prerelease view so that it contains everything, but only promote stable packages to the Release view.

It would be nice to have an option in the task to only run if the package version is stable. That would enable me to put it in my "prod stage" and but only run if the package version is stable. I might release pre-releases to NuGet, so the stage alone isn't sufficient.

**Comment by renevanosnabrugge** [comment]
And what is your decision criteria for “stable” ?

Verstuurd vanaf mijn iPhone

Op 2 aug. 2019 om 14:22 heeft Oren Novotny <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


My scenario is this -- I want to always promote packages to the Prerelease view so that it contains everything, but only promote stable packages to the Release view.

It would be nice to have an option in the task to only run if the package version is stable. That would enable me to put it in my "prod stage" and but only run if the package version is stable. I might release pre-releases to NuGet, so the stage alone isn't sufficient.

**Comment by onovotny** [comment]
Stable is not having any prerelease tag in it, at least that's how it works on NuGet. Not sure if the same applies to other package types this tool supports?

**Comment by renevanosnabrugge** [comment]
You mean a semver tag? Or a real tag in the feed? In my opinion the release view is to overcome the Semver tag. Do not reversion the package but promote it to another view.

Verstuurd vanaf mijn iPhone

Op 2 aug. 2019 om 19:12 heeft Oren Novotny <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Stable is not having any prerelease tag in it, at least that's how it works on NuGet. Not sure if the same applies to other package types this tool supports?

**Comment by NightOwl888** [comment]
Seems like a trivial thing to do without changing the task. You can definitively check whether a version number is a prerelease by whether it has a `-` in it, which can be a condition whether or not to run the task.

```
# Always push to Prerelease
- task: rvo.vsts-promotepackage-task.vsts-promotepackage-task.rvo-vsts-promotepackage-task@2
  displayName: 'Promote package to Prerelease View'
  inputs:
    feed: '$(ArtifactFeedID)'
    releaseView: 'Prerelease'
    inputType: packageFiles
    packagesDirectory: '$(Build.ArtifactStagingDirectory)/$(NuGetArtifactName)'

# Only push to Release if we are stable
- task: rvo.vsts-promotepackage-task.vsts-promotepackage-task.rvo-vsts-promotepackage-task@2
  displayName: 'Promote package to Release View'
  condition: and(succeeded(), not(contains(variables['Build.BuildNumber'], '-')))
  inputs:
    feed: '$(ArtifactFeedID)'
    releaseView: 'Release'
    inputType: packageFiles
    packagesDirectory: '$(Build.ArtifactStagingDirectory)/$(NuGetArtifactName)'
```
